name: products
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  dio: ^5.0.0
  flex_color_scheme: ^6.1.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.2.0
  flutter_staggered_animations: ^1.1.1
  freezed_annotation: ^2.2.0
  gap: ^2.0.1
  google_fonts: ^4.0.3
  json_annotation: ^4.8.0
  retrofit: ^4.0.1
  riverpod: ^2.2.0
  riverpod_annotation: ^1.2.1

dev_dependencies:
  build_runner: ^2.3.3
  change_case: ^1.1.0
  custom_lint: ^0.2.5
  dart_code_metrics: ^5.6.0
  dart_code_metrics_presets: ^1.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  retrofit_generator: ^5.0.0
  riverpod_generator: ^1.2.0
  riverpod_lint: ^1.0.1
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
